name: "Cargo Cross Action"
description: "A configurable GitHub Action to build, test, and check Rust projects with cross-compilation support"

branding:
  icon: "package"
  color: "orange"

inputs:
  command:
    description: "Command to execute (build, test, check)"
    required: false
    default: "build"
  target:
    description: "Rust target triple(s) to build for (newline-separated recommended, comma-separated also supported)"
    required: false
    default: ""
  targets:
    description: "Rust target triple(s) to build for (newline-separated recommended, comma-separated also supported)"
    required: false
    default: ""
  profile:
    description: "Build profile (debug or release)"
    required: false
    default: "release"
  features:
    description: "Comma-separated list of features to activate"
    required: false
  no-default-features:
    description: "Do not activate default features"
    required: false
    default: "false"
  all-features:
    description: "Activate all available features"
    required: false
    default: "false"
  package:
    description: "Package to build (workspace member)"
    required: false
  exclude:
    description: "Exclude packages from the build (must be used with workspace)"
    required: false
  bin:
    description: "Binary target to build"
    required: false
  workspace:
    description: "Build all workspace members"
    required: false
    default: "false"
  manifest-path:
    description: "Path to Cargo.toml"
    required: false
  source-dir:
    description: "The directory containing the Rust project to build"
    required: false
    default: ${{ github.workspace }}
  github-proxy-mirror:
    description: "GitHub proxy mirror URL for downloading cross compilers"
    required: false
  cross-compiler-dir:
    description: "Directory to store cross compilers"
    required: false
  ndk-version:
    description: "Android NDK version for Android builds"
    required: false
    default: "r27"
  glibc-version:
    description: "Glibc version for GNU targets (e.g., 2.31, 2.42). Leave empty for default version"
    required: false
  iphone-sdk-version:
    description: "iPhone SDK version for iOS targets (e.g., 17.0, 18.2, 26.2). On non-macOS uses bundled SDKs, on macOS uses installed Xcode SDK. Leave empty for default version (26.2)"
    required: false
  iphone-sdk-path:
    description: "Override iPhoneOS SDK path for device targets (skips version lookup). Only for native macOS builds"
    required: false
  iphone-simulator-sdk-path:
    description: "Override iPhoneSimulator SDK path for simulator targets (skips version lookup). Only for native macOS builds"
    required: false
  macos-sdk-version:
    description: "macOS SDK version for Darwin targets (e.g., 14.0, 15.2, 26.2). On non-macOS uses bundled SDKs, on macOS uses installed Xcode SDK. Leave empty for default version (26.2)"
    required: false
  macos-sdk-path:
    description: "Override macOS SDK path directly (skips version lookup). Only for native macOS builds"
    required: false
  freebsd-version:
    description: "FreeBSD version for FreeBSD targets (13 or 14). Default is 13"
    required: false
  qemu-version:
    description: "QEMU version for Linux cross-compilation runner"
    required: false
    default: "v10.2.0-rc1"
  use-default-linker:
    description: "Use system default linker (no cross-compiler download)"
    required: false
    default: "false"
  cc:
    description: "Force set the C compiler"
    required: false
  cxx:
    description: "Force set the C++ compiler"
    required: false
  ar:
    description: "Force set the archiver for target"
    required: false
  linker:
    description: "Force set the linker for target"
    required: false
  cflags:
    description: "C compiler flags (cc crate)"
    required: false
  cxxflags:
    description: "C++ compiler flags (cc crate)"
    required: false
  cxxstdlib:
    description: "C++ standard library to link against (cc crate)"
    required: false
  rustc-wrapper:
    description: "Compiler wrapper for caching tools like sccache, ccache, etc."
    required: false
  enable-sccache:
    description: "Enable sccache for compilation caching (automatically sets rustc-wrapper)"
    required: false
    default: "false"
  sccache-dir:
    description: "Sccache local cache directory"
    required: false
  sccache-cache-size:
    description: "Maximum sccache cache size (e.g., 2G, 10G)"
    required: false
  sccache-idle-timeout:
    description: "Sccache daemon idle timeout in seconds (0 for permanent)"
    required: false
  sccache-log:
    description: "Sccache log level (error, warn, info, debug, trace)"
    required: false
  sccache-no-daemon:
    description: "Disable sccache background daemon"
    required: false
    default: "false"
  sccache-direct:
    description: "Enable sccache preprocessor caching"
    required: false
    default: "false"
  sccache-s3-bucket:
    description: "S3 bucket name for sccache storage"
    required: false
  sccache-s3-endpoint:
    description: "S3 endpoint for sccache (e.g., for R2, MinIO)"
    required: false
  sccache-s3-region:
    description: "S3 region for sccache"
    required: false
  sccache-redis-endpoint:
    description: "Redis endpoint URL for sccache"
    required: false
  sccache-gcs-bucket:
    description: "Google Cloud Storage bucket for sccache"
    required: false
  sccache-azure-connection-string:
    description: "Azure storage connection string for sccache"
    required: false
  sccache-gha-enabled:
    description: "Enable GitHub Actions cache backend for sccache"
    required: false
    default: "false"
  cc-no-defaults:
    description: "Disable default cc crate compiler flags (sets CRATE_CC_NO_DEFAULTS)"
    required: false
    default: "false"
  cc-shell-escaped-flags:
    description: "Parse *FLAGS variables using shell argument parsing rules (cc crate)"
    required: false
    default: "false"
  cc-enable-debug:
    description: "Enable cc crate debug output to see compiler commands"
    required: false
    default: "false"
  rustflags:
    description: "Additional rustflags"
    required: false
  static-crt:
    description: "[DEPRECATED: Use crt-static instead] Control CRT linking mode: 'true' for static (+crt-static), 'false' for dynamic (-crt-static), empty for default behavior"
    required: false
    default: ""
    deprecationMessage: "static-crt is deprecated, use crt-static instead"
  crt-static:
    description: "Control CRT linking mode: 'true' for static (+crt-static), 'false' for dynamic (-crt-static), empty for default behavior"
    required: false
    default: ""
  panic-immediate-abort:
    description: 'Enable panic=immediate-abort strategy (adds -Zunstable-options -Cpanic=immediate-abort, enables build-std). This is a real panic strategy since nightly-2025-09-24, can also be set via `panic = "immediate-abort"` in Cargo.toml'
    required: false
    default: ""
  build-std:
    description: "Use -Zbuild-std for building standard library from source (true for default, or specify crates like 'core,alloc')"
    required: false
    default: "false"
  build-std-features:
    description: "Features to enable for -Zbuild-std (e.g., panic_immediate_abort, optimize_for_size)"
    required: false
  clean-cache:
    description: "Clean build cache before building"
    required: false
    default: "false"
  no-strip:
    description: "Do not strip binaries"
    required: false
    default: "false"
  verbose:
    description: "Verbose level (0-4, or 'true' for level 1)"
    required: false
    default: "0"
  show-all-targets:
    description: "Show all supported targets and exit"
    required: false
    default: "false"
  args:
    description: "Additional arguments to pass to cargo build"
    required: false
  passthrough-args:
    description: "Arguments to pass after -- (e.g., for cargo test: --show-output)"
    required: false
  cross-args:
    description: "Additional cross arguments"
    required: false
  toolchain:
    description: "Rust toolchain to use (stable, nightly, etc.)"
    required: false
  cargo-trim-paths:
    description: "Set CARGO_TRIM_PATHS environment variable for reproducible builds"
    required: false
  trim-paths:
    description: "Set CARGO_TRIM_PATHS environment variable for reproducible builds"
    required: false
  no-embed-metadata:
    description: "Add -Zno-embed-metadata flag to cargo"
    required: false
    default: "false"
  rustc-bootstrap:
    description: "Set RUSTC_BOOTSTRAP environment variable (1 for all crates, -1 for stable behavior, or crate_name for specific crate)"
    required: false
  target-dir:
    description: "Directory for all generated artifacts"
    required: false
  bins:
    description: "Build all binary targets"
    required: false
    default: "false"
  lib:
    description: "Build only the library target"
    required: false
    default: "false"
  example:
    description: "Example target to build"
    required: false
  examples:
    description: "Build all example targets"
    required: false
    default: "false"
  test:
    description: "Integration test to build"
    required: false
  tests:
    description: "Build all test targets"
    required: false
    default: "false"
  bench:
    description: "Benchmark target to build"
    required: false
  benches:
    description: "Build all benchmark targets"
    required: false
    default: "false"
  all-targets:
    description: "Build all targets (equivalent to --lib --bins --tests --benches --examples)"
    required: false
    default: "false"
  release:
    description: "Build optimized artifacts with the release profile"
    required: false
    default: "false"
  quiet:
    description: "Do not print cargo log messages"
    required: false
    default: "false"
  message-format:
    description: "The output format for diagnostic messages"
    required: false
  ignore-rust-version:
    description: "Ignore rust-version specification in packages"
    required: false
    default: "false"
  locked:
    description: "Asserts that exact same dependencies are used as Cargo.lock"
    required: false
    default: "false"
  offline:
    description: "Prevents Cargo from accessing the network"
    required: false
    default: "false"
  frozen:
    description: "Equivalent to specifying both --locked and --offline"
    required: false
    default: "false"
  lockfile-path:
    description: "Path to Cargo.lock (unstable, requires nightly)"
    required: false
  jobs:
    description: "Number of parallel jobs to run"
    required: false
  keep-going:
    description: "Build as many crates as possible, don't abort on first failure"
    required: false
    default: "false"
  future-incompat-report:
    description: "Displays a future-incompat report for warnings"
    required: false
    default: "false"
  artifact-dir:
    description: "Copy final artifacts to this directory (unstable, requires nightly)"
    required: false
  color:
    description: "Control when colored output is used (auto, always, never)"
    required: false
  build-plan:
    description: "Outputs a series of JSON messages (unstable, requires nightly)"
    required: false
    default: "false"
  timings:
    description: "Output information about compilation timing"
    required: false
  cargo-cwd:
    description: "Change current working directory before executing"
    required: false

outputs:
  targets:
    description: "Targets that were processed"
    value: ${{ steps.execute.outputs.targets }}

runs:
  using: "composite"
  steps:
    - name: Setup Rustup
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Show all targets
      if: ${{ inputs.show-all-targets == 'true' }}
      shell: bash
      working-directory: ${{ inputs.source-dir }}
      run: |
        "${{ github.action_path }}/cross.sh" --show-all-targets

    - name: Execute
      id: execute
      if: ${{ inputs.show-all-targets == 'false' }}
      shell: bash
      working-directory: ${{ inputs.source-dir }}
      env:
        COMMAND: ${{ inputs.command }}
        TARGETS: ${{ inputs.target || inputs.targets }}
        PROFILE: ${{ inputs.profile }}
        FEATURES: ${{ inputs.features }}
        NO_DEFAULT_FEATURES: ${{ inputs.no-default-features }}
        ALL_FEATURES: ${{ inputs.all-features }}
        PACKAGE: ${{ inputs.package }}
        EXCLUDE: ${{ inputs.exclude }}
        BIN_TARGET: ${{ inputs.bin }}
        BUILD_BINS: ${{ inputs.bins }}
        BUILD_LIB: ${{ inputs.lib }}
        EXAMPLE_TARGET: ${{ inputs.example }}
        BUILD_EXAMPLES: ${{ inputs.examples }}
        TEST_TARGET: ${{ inputs.test }}
        BUILD_TESTS: ${{ inputs.tests }}
        BENCH_TARGET: ${{ inputs.bench }}
        BUILD_BENCHES: ${{ inputs.benches }}
        BUILD_ALL_TARGETS: ${{ inputs.all-targets }}
        BUILD_WORKSPACE: ${{ inputs.workspace }}
        MESSAGE_FORMAT: ${{ inputs.message-format }}
        IGNORE_RUST_VERSION: ${{ inputs.ignore-rust-version }}
        LOCKED: ${{ inputs.locked }}
        OFFLINE: ${{ inputs.offline }}
        FROZEN: ${{ inputs.frozen }}
        LOCKFILE_PATH: ${{ inputs.lockfile-path }}
        JOBS: ${{ inputs.jobs }}
        KEEP_GOING: ${{ inputs.keep-going }}
        FUTURE_INCOMPAT_REPORT: ${{ inputs.future-incompat-report }}
        ARTIFACT_DIR: ${{ inputs.artifact-dir }}
        COLOR: ${{ inputs.color }}
        BUILD_PLAN: ${{ inputs.build-plan }}
        TIMINGS: ${{ inputs.timings }}
        CARGO_CWD: ${{ inputs.cargo-cwd }}
        MANIFEST_PATH: ${{ inputs.manifest-path }}
        GH_PROXY: ${{ inputs.github-proxy-mirror }}
        CROSS_COMPILER_DIR: ${{ inputs.cross-compiler-dir }}
        NDK_VERSION: ${{ inputs.ndk-version }}
        GLIBC_VERSION: ${{ inputs.glibc-version }}
        IPHONE_SDK_VERSION: ${{ inputs.iphone-sdk-version }}
        IPHONE_SDK_PATH: ${{ inputs.iphone-sdk-path }}
        IPHONE_SIMULATOR_SDK_PATH: ${{ inputs.iphone-simulator-sdk-path }}
        MACOS_SDK_VERSION: ${{ inputs.macos-sdk-version }}
        MACOS_SDK_PATH: ${{ inputs.macos-sdk-path }}
        FREEBSD_VERSION: ${{ inputs.freebsd-version }}
        QEMU_VERSION: ${{ inputs.qemu-version }}
        USE_DEFAULT_LINKER: ${{ inputs.use-default-linker }}
        CC: ${{ inputs.cc }}
        CXX: ${{ inputs.cxx }}
        AR: ${{ inputs.ar }}
        LINKER: ${{ inputs.linker }}
        CFLAGS: ${{ inputs.cflags }}
        CXXFLAGS: ${{ inputs.cxxflags }}
        CXXSTDLIB: ${{ inputs.cxxstdlib }}
        RUSTC_WRAPPER: ${{ inputs.rustc-wrapper }}
        ENABLE_SCCACHE: ${{ inputs.enable-sccache }}
        SCCACHE_DIR: ${{ inputs.sccache-dir }}
        SCCACHE_CACHE_SIZE: ${{ inputs.sccache-cache-size }}
        SCCACHE_IDLE_TIMEOUT: ${{ inputs.sccache-idle-timeout }}
        SCCACHE_LOG: ${{ inputs.sccache-log }}
        SCCACHE_NO_DAEMON: ${{ inputs.sccache-no-daemon == 'true' && '1' || '' }}
        SCCACHE_DIRECT: ${{ inputs.sccache-direct == 'true' && 'true' || '' }}
        SCCACHE_BUCKET: ${{ inputs.sccache-s3-bucket }}
        SCCACHE_ENDPOINT: ${{ inputs.sccache-s3-endpoint }}
        SCCACHE_REGION: ${{ inputs.sccache-s3-region }}
        SCCACHE_REDIS_ENDPOINT: ${{ inputs.sccache-redis-endpoint }}
        SCCACHE_GCS_BUCKET: ${{ inputs.sccache-gcs-bucket }}
        SCCACHE_AZURE_CONNECTION_STRING: ${{ inputs.sccache-azure-connection-string }}
        SCCACHE_GHA_CACHE_TO: ${{ inputs.sccache-gha-enabled == 'true' && github.ref || '' }}
        SCCACHE_GHA_CACHE_FROM: ${{ inputs.sccache-gha-enabled == 'true' && format('{0},{1}', github.ref, github.base_ref) || '' }}
        CRATE_CC_NO_DEFAULTS: ${{ inputs.cc-no-defaults == 'true' && '1' || '' }}
        CC_SHELL_ESCAPED_FLAGS: ${{ inputs.cc-shell-escaped-flags == 'true' && '1' || '' }}
        CC_ENABLE_DEBUG_OUTPUT: ${{ inputs.cc-enable-debug == 'true' && '1' || '' }}
        ADDITIONAL_RUSTFLAGS: ${{ inputs.rustflags }}
        CRT_STATIC: ${{ inputs.crt-static != '' && inputs.crt-static || inputs.static-crt }}
        PANIC_IMMEDIATE_ABORT: ${{ inputs.panic-immediate-abort }}
        BUILD_STD: ${{ inputs.build-std }}
        BUILD_STD_FEATURES: ${{ inputs.build-std-features }}
        CLEAN_CACHE: ${{ inputs.clean-cache }}
        NO_STRIP: ${{ inputs.no-strip }}
        VERBOSE_LEVEL: ${{ inputs.verbose == 'true' && '1' || inputs.verbose }}
        CARGO_ARGS: ${{ inputs.args }}
        CARGO_PASSTHROUGH_ARGS: ${{ inputs.passthrough-args && format('-- {0}', inputs.passthrough-args) || '' }}
        TOOLCHAIN: ${{ inputs.toolchain }}
        CARGO_TRIM_PATHS: ${{ inputs.cargo-trim-paths || inputs.trim-paths }}
        NO_EMBED_METADATA: ${{ inputs.no-embed-metadata }}
        RUSTC_BOOTSTRAP: ${{ inputs.rustc-bootstrap }}
        CARGO_TARGET_DIR: ${{ inputs.target-dir }}
        QUIET: ${{ inputs.quiet }}
        RELEASE: ${{ inputs.release }}
      run: |
        cargo run ${{ github.action_path }} -- ${{ inputs.cross-args }}
